// ESLint flat config (ESLint 9) for the parish portal.
//
// `eslint-config-next@15.5.25` still ships the legacy (eslintrc) shape, so it is bridged with
// `FlatCompat` — this is the documented Next.js 15 setup. The rules come from
// `next/core-web-vitals` (core Next.js rules + the Web Vitals escalations on top of
// `next/recommended`).
//
// Run with `pnpm run lint`.

import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const baseDirectory = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory });

const config = [
  {
    ignores: [
      ".next/**",
      "apps/*/.next/**",
      "node_modules/**",
      "apps/*/node_modules/**",
      // Generated by Next.js; declares its own triple-slash references.
      "next-env.d.ts",
      "apps/*/next-env.d.ts",
      // Local scratch/agent material, SQL migrations and docs are not JS/TS.
      ".scratch/**",
      "supabase/**",
      "memory-bank/**",
      "docs/**",
    ],
  },
  ...compat.extends("next/core-web-vitals"),
  {
    settings: {
      next: {
        rootDir: ["apps/web/"],
      },
    },
  },
];

export default config;
