// packages/data-access/src/navigation/seed-nav.ts
// Baseline navigation items preserving bit-for-bit parity with the portal's hardcoded header links.

import type { NavigationMenuItem, PublicNavItem } from "@church-site/domain";

export const SEED_NAVIGATION_ITEMS: NavigationMenuItem[] = [
  {
    id: "nav-item-001",
    key: "home",
    labelAr: "الرئيسية",
    labelEn: "Home",
    href: "/",
    section: "main",
    parentId: null,
    sortOrder: 1,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-002",
    key: "about",
    labelAr: "عن الكنيسة",
    labelEn: "About",
    href: "/about",
    section: "main",
    parentId: null,
    sortOrder: 2,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-002-1",
    key: "about-main",
    labelAr: "عن الكنيسة",
    labelEn: "About Parish",
    href: "/about",
    section: "main",
    parentId: "nav-item-002",
    sortOrder: 1,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-002-2",
    key: "about-history",
    labelAr: "تاريخ الكنيسة والشفعاء",
    labelEn: "History & Patrons",
    href: "/about/history",
    section: "main",
    parentId: "nav-item-002",
    sortOrder: 2,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-002-3",
    key: "about-altars",
    labelAr: "المذابح الثلاثة والمزارات",
    labelEn: "Altars & Shrines",
    href: "/about/altars",
    section: "main",
    parentId: "nav-item-002",
    sortOrder: 3,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-002-4",
    key: "about-clergy",
    labelAr: "مجمع الآباء الكهنة",
    labelEn: "Clergy",
    href: "/about/clergy",
    section: "main",
    parentId: "nav-item-002",
    sortOrder: 4,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-003",
    key: "masses",
    labelAr: "مواعيد القداسات",
    labelEn: "Liturgy Schedules",
    href: "/masses",
    section: "main",
    parentId: null,
    sortOrder: 3,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-004",
    key: "events",
    labelAr: "الفعاليات",
    labelEn: "Events",
    href: "/events",
    section: "main",
    parentId: null,
    sortOrder: 4,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-005",
    key: "meetings",
    labelAr: "التربية الكنسية",
    labelEn: "Sunday School & Youth",
    href: "/meetings",
    section: "main",
    parentId: null,
    sortOrder: 5,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-006",
    key: "ministries",
    labelAr: "الخدمات الرعوية",
    labelEn: "Ministries",
    href: "/ministries",
    section: "main",
    parentId: null,
    sortOrder: 6,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-007",
    key: "education",
    labelAr: "المدارس والمعاهد",
    labelEn: "Education & Institutes",
    href: "/education",
    section: "main",
    parentId: null,
    sortOrder: 7,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-008",
    key: "activities",
    labelAr: "الأنشطة الرعوية",
    labelEn: "Activities",
    href: "/activities",
    section: "main",
    parentId: null,
    sortOrder: 8,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-009",
    key: "services",
    labelAr: "خدمات الكنيسة",
    labelEn: "Church Services",
    href: "/services",
    section: "main",
    parentId: null,
    sortOrder: 9,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-010",
    key: "condolence",
    labelAr: "حجز قاعة العزاء",
    labelEn: "Condolence Booking",
    href: "/condolence",
    section: "main",
    parentId: null,
    sortOrder: 10,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-011",
    key: "live",
    labelAr: "البث المباشر",
    labelEn: "Live Stream",
    href: "/live",
    section: "main",
    parentId: null,
    sortOrder: 11,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-012",
    key: "bible",
    labelAr: "الكتاب المقدس",
    labelEn: "Holy Bible",
    href: "/bible",
    section: "main",
    parentId: null,
    sortOrder: 12,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-013",
    key: "donations",
    labelAr: "التبرعات",
    labelEn: "Donations",
    href: "/donations",
    section: "main",
    parentId: null,
    sortOrder: 13,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-014",
    key: "contact",
    labelAr: "اتصل بنا",
    labelEn: "Contact Us",
    href: "/contact",
    section: "main",
    parentId: null,
    sortOrder: 14,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },

  // Secondary items (Mobile Drawer & Footer)
  {
    id: "nav-item-015",
    key: "gallery",
    labelAr: "معرض الصور",
    labelEn: "Photo Gallery",
    href: "/gallery",
    section: "secondary",
    parentId: null,
    sortOrder: 1,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-016",
    key: "sermons",
    labelAr: "العظات والتسجيلات",
    labelEn: "Sermons",
    href: "/sermons",
    section: "secondary",
    parentId: null,
    sortOrder: 2,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
  {
    id: "nav-item-017",
    key: "privacy",
    labelAr: "الخصوصية والشروط",
    labelEn: "Privacy & Terms",
    href: "/privacy",
    section: "secondary",
    parentId: null,
    sortOrder: 3,
    isActive: true,
    isPublic: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    createdBy: null,
    updatedBy: null,
  },
];

/**
 * Builds the public-safe navigation hierarchy matching Header.tsx requirements.
 */
export function buildPublicNavHierarchy(items: NavigationMenuItem[]): {
  main: PublicNavItem[];
  secondary: PublicNavItem[];
} {
  const activeItems = items.filter((i) => i.isActive && i.isPublic);

  const mainTop = activeItems
    .filter((i) => i.section === "main" && !i.parentId)
    .sort((a, b) => a.sortOrder - b.sortOrder);

  const mainWithChildren: PublicNavItem[] = mainTop.map((top) => {
    const children = activeItems
      .filter((i) => i.parentId === top.id)
      .sort((a, b) => a.sortOrder - b.sortOrder)
      .map((c) => ({
        id: c.id,
        key: c.key,
        labelAr: c.labelAr,
        labelEn: c.labelEn,
        href: c.href,
        section: c.section,
        parentId: c.parentId,
        sortOrder: c.sortOrder,
      }));

    return {
      id: top.id,
      key: top.key,
      labelAr: top.labelAr,
      labelEn: top.labelEn,
      href: top.href,
      section: top.section,
      parentId: null,
      sortOrder: top.sortOrder,
      ...(children.length > 0 ? { children } : {}),
    };
  });

  const secondaryItems: PublicNavItem[] = activeItems
    .filter((i) => i.section === "secondary")
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map((s) => ({
      id: s.id,
      key: s.key,
      labelAr: s.labelAr,
      labelEn: s.labelEn,
      href: s.href,
      section: s.section,
      parentId: s.parentId,
      sortOrder: s.sortOrder,
    }));

  return {
    main: mainWithChildren,
    secondary: secondaryItems,
  };
}

export const SEED_PUBLIC_NAVIGATION = buildPublicNavHierarchy(SEED_NAVIGATION_ITEMS);
